# src/Gregumo/StarsRentalBundle/Resources/config/services.yml

services:

    gregumo_starsrental.utils.booking_upgrader:
        class:     Gregumo\StarsRentalBundle\Utils\BookingUpgrader
        arguments: [ "@doctrine.orm.entity_manager" ]
